name: file_cryptor
description: File Cryptor
version: 0.0.1
author: Khaydarov Abdulaminkhon
homepage: https://github.com/webdastur/file_cryptor

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.0
  path: ^1.8.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
